kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: LoadBalancer # Minikube tunnel command is required
  selector:
    app: frontend
  ports:
    - port: 3001 # Enduser access this port 
      targetPort: 3000 # containerPort running in the Pod